name: Init new issue tickets
run-name: New issue - ${{github.event.issue.title}}

on:
  issues:
    types: [opened]

jobs:
  init-issue:
    runs-on: ubuntu-latest
    name: initialize new issue ticket
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: set label on issue
        id: set-issue-label
        uses: JonahsOrg/workflows/set-issue-label@v0.0.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo_id: ${{ github.event.repository.node_id }}
          issue_id: ${{ github.event.issue.node_id }}
          label: 'test'

      - name: create a linked branch
        id: create-linked-branch
        uses: JonahsOrg/workflows/create-linked-branch@v0.0.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo_id: ${{ github.event.repository.node_id }}
          issue_id: ${{ github.event.issue.node_id }}
          issue_title: ${{ github.event.issue.title }}
          branch_to_copy: 'main'

      - name: create a pull request
        id: create-pr
        if: steps.create-linked-branch.outcome == 'success'
        uses: JonahsOrg/workflows/create-pr@v0.0.6
        with:
          linked_branch_name: ${{steps.create-linked-branch.outputs.linkedBranchName}}
          token: ${{ secrets.GITHUB_TOKEN }}
          repo_id: ${{ github.event.repository.node_id }}
          issue_title: ${{ github.event.issue.title }}
          merge_into_branch: 'development'

      - name: change the status of a linked project card
        id: set-status
        uses: JonahsOrg/workflows/set-status@v0.0.6
        with:
          token: ${{ secrets.ORGANIZATION_PAT }}
          issue_id: ${{ github.event.issue.node_id }}
          set_status_to: 'In Development'

      - name: create comment on new issue
        id: create-comment
        uses: JonahsOrg/workflows/create-comment@v0.0.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          node_id: ${{ github.event.issue.node_id }}
          message: 'this is a test message.'

      - name: Print Output
        id: output
        run: echo "completed function call"
