name: Init new issue tickets
run-name: New issue - ${{github.event.issue.title}}

on:
  issues:
    types: [opened]

jobs:
  initialize-new-issue:
    runs-on: ubuntu-latest
    name: set label on labelable
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: set label "${{vars.LABEL_TO_ADD_TO_ISSUE}}" on issue ${{ github.event.issue.number }}
        id: set-issue-label
        uses: JonahsOrg/workflows/set-issue-label@v0.0.4
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_id: ${{ github.event.issue.node_id }}
          label: ${{vars.LABEL_TO_ADD_TO_ISSUE}}

      - name: create a linked branch
        id: create-linked-branch
        uses: JonahsOrg/workflows/create-linked-branch@v0.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          repo_id: ${{ github.event.repository.node_id }}
          issue_id: ${{ github.event.issue.node_id }}
          issue_title: ${{ github.event.issue.title }}
          branch_to_copy: ${{vars.BRANCH_TO_COPY}}

      - name: create a pull request
        id: create-pr
        if: steps.create-linked-branch.outcome == 'success'
        uses: JonahsOrg/workflows/create-pr@v0.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo_id: ${{ github.event.repository.node_id }}
          issue_title: ${{ github.event.issue.title }}
          merge_into_branch: ${{vars.MERGE_INTO_BRANCH}}

      - name: Print Output
        id: output
        run: echo "completed function call"
